### ISSUE TITLE
bug(docs): toc is not sticky

### ISSUE THREAD

**Issue by donroyco** [angular/material.angular.io#257]
Bug.

**Mozilla Firefox: _Not sticky_**
When navigation in Mozilla Firefox version 55.0.2 on a [components page](https://material.angular.io/components/icon/overview) while scrolling down, the table of contents won't stay at the top of the viewport, but just scrolls along with the rest of the content.

![toc-scroll](https://user-images.githubusercontent.com/1763537/29995337-338c04c2-8fe7-11e7-93a8-8c83f7e03a9a.gif)

**Apple Safari: _Bottom of page_**
In Apple Safari, version 10.1.1, the table of contents is at the bottom of the page (below screenshot) and also not sticky, but this may be a side effect of #247 | #248 

![toc-safari](https://user-images.githubusercontent.com/1763537/29995356-95e696dc-8fe7-11e7-8190-b27fa5ac5329.png)

**Browser**
Mozilla Firefox, version 55.0.2
Apple Safari, version 10.1.1

**What else?**
No errors in console.

**Comment by amcdnl** [comment]
In Safari, you can toggle various different parent elements display properties and it starts working. For instance, toggling this ![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/42a4935a-767e-49cd-b044-8ecf15f3c13e/2017-09-02_09-43-12.png) in the dev tools makes it work, however, if you set it via css or even programmatically in JS, it doesn't work. I'm guessing this is a reflow issue.

**Comment by donroyco** [comment]
@amcdnl Thanks for looking into this.

**Comment by annieyw** [comment]
Fixed in https://github.com/oktav777/material.angular.io/pull/1

**Comment by Splaktar** [comment]
It looks like PR https://github.com/angular/material.angular.io/pull/362 is still open to solve this. Though it hasn't been rebased in a few years. I'm not sure if it's still relevant/needed?

**Comment by Splaktar** [comment]
I closed #362 since similar changes were made in PR https://github.com/angular/material.angular.io/pull/840, but they did not fix the sticky TOC issues.

**Comment by Splaktar** [comment]
@tommyc38 is correct in https://github.com/angular/material.angular.io/issues/916#issue-801031281 that `overflow: hidden` in the component-sidenav.scss is what is breaking the sticky TOC.

But that was added to fix https://github.com/angular/components/issues/20313 and in the PR I actually [raised a comment](https://github.com/angular/material.angular.io/pull/856#issuecomment-675613251) that I didn't think that this fix was appropriate.

I'll investigate finding a solution that solves both issues.
