### ISSUE TITLE
Scroll down does not work on Safari.

### ISSUE THREAD

**Issue by jeongjoonlee3** [angular/material.angular.io#84]
https://material.angular.io/components
In context section next to left navigation bar, the scroll does not work on Safari.

The console shows this message only on Safari.
Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) https://ajax.googleapis.com/ajax/libs/hammerjs/2.0.8/hammer.min.js.map

**Comment by tianyangj** [comment]
I think this issue is related to https://github.com/angular/material.angular.io/issues/71. https://github.com/angular/material.angular.io/pull/82 is merged to master.

**Comment by IvanYurchenko** [comment]
Still not fixed, I have the same problem.

**Comment by avalonabecker** [comment]
Still not fixed, I have the same problem in Safari Version 10.0.3 (11602.4.8.0.1)

**Comment by DevVersion** [comment]
@andrewseguin This should be fixed? Just needs to wait for a new publish of the docs right.

**Comment by jelbourn** [comment]
Seems to work on Safari now.

**Comment by JeanPerriault** [comment]
Looks like the issue is back. Main content is not scrollable on Safari Version 10.1.2 (12603.3.8) / Mac OS Sierra version 10.12.6. Should I raise a new issue here?

**Comment by willshowell** [comment]
@JeanPerriault it has been fixed on the docs site with https://github.com/angular/material.angular.io/pull/248, but has not yet been deployed.

**Comment by JeanPerriault** [comment]
Wonderfull thx @willshowell

**Comment by JeanPerriault** [comment]
Ok this is fixed now but it looks like it led to another issue, the table of content is now displayed at the bottom of the page, and doesn't stick to top.

**Comment by mark922** [comment]
Still facing the same issue. Not able to scroll [https://material.angular.io/components](https://material.angular.io/components/)  page in Safari.

Safari - Version 10.1.2 (12603.3.8)) 
Mac OS - Version 10.12.6
